config/routes.rb
Wayprint::Application.routes.draw do
  get "dashboard/index"
  resources :waypoints

  root 'dashboard#index'

  

end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @waypoints = Waypoint.all
  end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]

  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
    gon.waypoints = Waypoint.all
    @waypoint = Waypoint.new
    @w = Waypoint.first
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
  end

  # GET /waypoints/1/edit
  def edit
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    @waypoint = Waypoint.new(waypoint_params)

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to waypoints_path, notice: 'Waypoint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @waypoint }
      else
        format.html { render action: 'new' }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to waypoints_path, notice: 'Waypoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:name, :location, :wayprint, :lat, :lng, :trip_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/dashboard/index.html.erb
<!-- Home Section -->
      <!-- Modal For Gallery -->
      <div class="modal fade" id="modal1" tabindex="-1" role="dialog">
        <div class="wrapper">
          <img data-dismiss="modal" class="img-responsive" src="sarahawaii.jpg" alt="">
          <h2 class="modal-title"><a href="http://sintel.org">Sarah in Maui</a></h2>
        </div><!-- /.content -->      
      </div><!-- /.modal -->

      <div class="modal fade" id="modal2" tabindex="-1" role="dialog">
        <div class="wrapper">
          <img data-dismiss="modal" class="img-responsive" src="img/sintel-snowscape.jpg" alt="">
          <h2 class="modal-title"><a href="http://sintel.org">Sintel Snowscape</a></h2>
        </div><!-- /.content -->      
      </div><!-- /.modal -->

      <div class="modal fade" id="modal3" tabindex="-1" role="dialog">
        <div class="wrapper">
          <img data-dismiss="modal" class="img-responsive" src="img/sintel-bamboo.jpg" alt="">
          <h2 class="modal-title"><a href="http://sintel.org">Sintel Bamboo</a></h2>
        </div><!-- /.content -->      
      </div><!-- /.modal -->

      
    <div id="home" class="section">
      <div class="container">
        <div class="gallery portfolio row">
          <ul>
            
            <% @waypoints.each do |waypoint| %>
              <li class="col-md-4 col-sm-4 col-xs-12 mix icons mix_all" data-cat="icons" style="display: inline-block; opacity: 1;">
                <a data-toggle="modal" href="#modal1" class="mix-cover gray">
                  <img class="horizontal" src="/assets/sarahawaii.jpg" alt="placeholder">
                  <span class="overlay"><span class="valign"></span><span class="title">Maui</span></span>
                </a>                          
              </li>
            <% end %>
    
          </ul>
        </div>        
        
      </div>
    </div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="favicon.ico">
  <title>Wayprint</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
 <!--[if lte IE 8]>
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.ie.css" />
 <![endif]-->
  <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
    
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="navbar" class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "WayPoints", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to(root_path, :class => 'filter active', :data => { :filter => 'all' }) do %>
          <i class="fa fa-globe"> </i> Trips<span class="arrow-left"></span>
        <% end %></li>
        <li><%= link_to(waypoints_path, :class => 'filter', :data => { :filter => 'icons' }) do %>
          <i class="fa fa-camera"> </i> Waypoints<span class="arrow-left"></span>
        <% end %></li>                 
        
        <li><a class="filter" data-filter="web" href="#"><i class="fa fa-magic"></i>Wishlist<span class="arrow-left"></span></a></li>
        <li><a class="filter" data-filter="portraits" href="#"><i class="fa fa-random"></i>Random<span class="arrow-left"></span></a></li>
        <li><a href="#"><i class="fa fa-laptop"></i>Account<span class="arrow-left"></span></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
  
      <%= yield %>

  <div id="footer" class="section">
    <br><p>Made by <a href="http://www.diligentagility.com">Diligent Agility</a></p>     
  </div>
</body>
</html>

app/views/waypoints/_form.html.erb
<%= form_for(@waypoint) do |f| %>
  <% if @waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% @waypoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :wayprint %><br>
    <%= f.text_area :wayprint %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.number_field :trip_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waypoints/edit.html.erb
<h1>Editing waypoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @waypoint %> |
<%= link_to 'Back', waypoints_path %>

app/views/waypoints/index.html.erb
<h3>Current Location coords</h3>
<p id="coords"></p>

<div id="map"></div>

<div id="wordpost">
  <%= form_for @waypoint do |f| %>
    <div class="field">
      <%= f.text_field :name, 
                    :class => "topcoat-text-input",
                    :placeholder => "Name",
                    :size => 74 
                    %>
    </div>
 
    <div class="field">
      <%= f.text_area :wayprint, 
                    :class => "topcoat-textarea", 
                    :rows => "4",
                    :cols => "73",
                    :placeholder => "Enter Text"
                     %>
    </div>

    <%= f.hidden_field :lat, :id => 'latitude_field'%><br>
    <%= f.text_field :lng, :id => 'longitude_field' %> lng(to be hidden)<br>
    <input type="file" class ="topcoat-button" /> Testing adding a pic<br/>
    <%= f.submit "Submit!"%>

  <% end %>
  <%= button_to_function "Cancel", '$("#wordpost").slideUp();', :class => "topcoat-button" %>
 </div>


  <div id="container">
    <div class="item">item 1</div>
    <div class="item w2">item 400</div>
    <div class="item">intem 345</div>
  </div>


<div class="topcoat-list">
  <h3 class="topcoat-list__header">Waypoints</h3>
    <ul class="topcoat-list__container">
      <% @waypoints.each do |waypoint| %>
    <li class="topcoat-list__item">
      <%= waypoint.wayprint %> | <%= link_to 'Edit', edit_waypoint_path(waypoint) %> | <%= link_to 'Destroy', waypoint, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
    <% end %>
  </ul>
</div>

app/views/waypoints/new.html.erb
<h1>New waypoint</h1>

<%= render 'form' %>

<%= link_to 'Back', waypoints_path %>

app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @waypoint.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @waypoint.location %>
</p>

<p>
  <strong>Wayprint:</strong>
  <%= @waypoint.wayprint %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @waypoint.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @waypoint.lng %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @waypoint.trip_id %>
</p>

<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
<%= link_to 'Back', waypoints_path %>